name: CI

on:
    push:
        branches:
            - 'feat/**'
        paths:
            - ./**
            - '!infra/.**'
            - '!script/.**'

env:
    IMAGE: ${{ vars.NCR_HOST }}/swns
    IMAGE_TAG: ${{ vars.NCR_HOST }}/swns:latest
    CONTAINER_NAME: swns-dj

jobs:
    lint:
        name: Check lint (black)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install black
              run: pip install black
            
            - name: check black
              run: black --check .
    
    build:
        needs: lint
        name: build image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: test
              run:
                docker compose -f docker/docker-compose_test.yml up -d --build
                docker compose -f docker/docker-compose_test.yml exec swns python manage.py test
            
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_HOST }}
                username: ${{ secrets.NCP_ACCESS_KEY }}
                password: ${{ secrets.NCP_SECRET_KEY }}
            
            - name: Get current timestamp
              id: image-tag
              run: echo "TIMESTAMP=$(date "+%s")" >> "$GITHUB_OUTPUT"

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: ../
                tags: ${{ env.IMAGE_TAG}}, ${{ env.IMAGE}}:${{ steps.image-tag.outputs.TIMESTAMP }}
                file: ./docker/Dockerfile_dj
                push: true

            - name: post test
              if: ${{ always() }}
              run: |
                docker compose -f docker/docker-compose_test.yml down










